-- phpMyAdmin SQL Dump
-- version 4.8.2
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Temps de generació: 15-11-2018 a les 15:52:07
-- Versió del servidor: 10.1.35-MariaDB
-- Versió de PHP: 7.2.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de dades: `balearskills`
--

-- --------------------------------------------------------

--
-- Estructura de la taula `establiment`
--

CREATE TABLE `establiment` (
  `id` int(11) NOT NULL,
  `nom` varchar(200) NOT NULL,
  `descripcio_cat` varchar(1000) NOT NULL,
  `descripcio_esp` varchar(1000) NOT NULL,
  `horari_cat` varchar(1000) NOT NULL,
  `horari_esp` varchar(1000) NOT NULL,
  `poblacio` varchar(200) NOT NULL,
  `adreca` varchar(200) NOT NULL,
  `telefon` varchar(200) NOT NULL,
  `web` varchar(200) NOT NULL,
  `preu` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Bolcament de dades per a la taula `establiment`
--

INSERT INTO `establiment` (`id`, `nom`, `descripcio_cat`, `descripcio_esp`, `horari_cat`, `horari_esp`, `poblacio`, `adreca`, `telefon`, `web`, `preu`) VALUES
(1, 'I Love Japo', 'I Love Japo Ã©s un restaurant japoneÌs que et porta un trosset de JapoÌn a Mallorca. Un restaurant que et captivarÃ  per la seva original decoraciÃ³ i l\'alegria que desprÃ¨n. L\'equip d\'I Love Japo porta 5 anys situat al barri de Santa Catalina oferint una oferta Ãºnica: sushi i menjar japonÃ¨s amb una bona relacioÌn qualitat-preu. Per la seva ubicaciÃ³ en una zona de gran activitat, resulta ideal per endinsar-se i descobrir les diverses propostes i combinacions de la seva fantÃ stica carta. La gastronoia i cultura japonesa es revelen en els seus plats. Des del sushi tradicional, els futomakis tempuritzats o degustant l\'autÃ¨ntica cuina tÃ­pica de les tavernes japoneses, com els takoyaki, les gyozas o les tradicionals broquetes (kushiyaki) fins a arribar a les postres perquÃ¨ visquis una experiÃ¨ncia inoblidable.', 'I Love Japo es un restaurante japoneÌs que te trae un trocito de JapoÌn a Mallorca. Un restaurante que te cautivaraÌ por su original decoracioÌn y la alegriÌa que desprende. El equipo de I Love Japo lleva 5 anÌƒos situado en el barrio de Santa Catalina ofreciendo una oferta uÌnica: sushi y comida japonesa con una buena relacioÌn calidad-precio. Por su ubicacioÌn en una zona de gran actividad, resulta ideal para adentrarse y descubrir las diversas propuestas y combinaciones de su fantaÌstica carta. La gastronomiÌa y cultura japonesa se revelan en sus platos. Desde el sushi tradicional, los futomakis tempurizados o degustando la auteÌntica comida tiÌpica de las tabernas japonesas, como los takoyaki, las gyozas o las tradicionales brochetas (kushiyaki) hasta llegar a los postres para que vivas una experiencia inolvidable. ', 'Tots els dies de 13:30 a 15:30h.', 'Todos los dÃ­as de 13:30 a 15:30h.', 'Palma', 'c/ Sant MagÃ­, 25', '971738321', 'www.ilovejapo.com/', 'entre 20 i 25 â‚¬'),
(2, 'Celler PagÃ¨s', 'Situat en plena Llotja de Palma, el Celler PagÃ¨s obre les portes allÃ  per l\'any 1956. Ã‰s un negoci familiar, que ha sabut mantenir la tradiciÃ³ al llarg de tres generacions. Per ell han passat personalitats de la talla de Lola Flores, Chavela Vargas, Gerhard SchrÃ¶eder ... Ofereix una cuina tradicional mallorquina, de temporada, tÃ­pica i casolana, la de sempre. Receptes familiars sempre millorades amb un toc de modernitat. Destaquen per un servei absolutament professional i atent, pendent de cada detall.', 'Situado en plena Lonja de Palma, el Celler PagÃ©s abre sus puertas allÃ¡ por el aÃ±o 1956. Es un negocio familiar, que ha sabido mantener la tradiciÃ³n a lo largo de tres generaciones. Por Ã©l han pasado personalidades de la talla de Lola Flores, Chavela Vargas, Gerhard SchrÃ¶ederâ€¦ Ofrecen una cocina tradicional mallorquina, de temporada, tÃ­pica y casera, la de siempre. Recetas familiares siempre mejoradas con un toque de modernidad. Destacan por un servicio absolutamente profesional y atento, pendiente de cada detalle. ', 'De 13.00h. a 15.30h i de 20.00 h. a 23.00 h. Diumenges i dilluns nit tancat.', 'De 13.00h. a 15.30h y de  20.00h. a 23.00h. Domingos y lunes noche cerrado.', 'Palma', 'Felipe BauzÃ¡, 2', '971726036', 'www.cellerpages.com', 'entre 10 i 15 â‚¬'),
(3, 'Es Siurell', 'Especialistes en pa amb oli, frit mallorquÃ­ i caragols. El pa amb oli estrella Ã©s el que rep el nom del restaurant, Pa amb oli Ã‰s Siurell. Un deliciÃ³s pa amb oli de verdures a la planxa acompanyat de sÃ­pia, o llom, o formatge de cabra. TambÃ© tenim l\'anomenat Pa amb oli MallorquÃ­, amb sobrassada, camaiot i formatge maonÃ¨s o el pa amb oli d\'ibÃ¨rics. Encara que sempre poden optar per demanar-nos que embotits desitgen. Tots els nostres postres, a excepciÃ³ dels gelats sÃ³n casolans.', 'Especialistas en pa amb oli , frito mallorquÃ­n y caracoles. El pa amb oli estrella es el que recibe el nombre del restaurante, Pa amb oli Es Siurell. Un delicioso pa amb oli de verduras a la plancha acompaÃ±ado de sepia, o lomo, o queso de cabra. TambiÃ©n tenemos el llamado Pa amb oli MallorquÃ­, con sobrasada, camaiot i queso mahonÃ©s o el pa amb oli de ibÃ©ricos. Aunque siempre pueden optar por pedirnos que embutidos desean. Todos nuestros postres, a excepciÃ³n de los helados son caseros.', 'De dilluns a dissabte de 8 a 23 hores.', 'De lunes a sÃ¡bado de 8 a 23 horas.', 'Palma', 'Carretera Valldemossa 12', '971781240', 'www.facebook.com/essiurell', 'entre 20 i 25 â‚¬'),
(4, 'Ca\'n Lluc', 'Restaurant reconegut per l\'excelÂ·lÃ¨ncia dels seus menÃºs de cuina casolana tradicional tant mediterrÃ nia com mallorquina. Amb una experiÃ¨ncia de moltÃ­ssims anys, Can Lluc ofereix una qualitat i servei excelÂ·lent a preus molt econÃ²mics.', 'Restaurante  reconocido por la excelencia de sus menÃºs de cocina casera tradicional tanto mediterrÃ¡nea como mallorquina. Con una experiencia de muchÃ­simos aÃ±os, Ca\'n Lluc ofrece una calidad y servicio excelente a precios muy econÃ³micos.', 'De 7:00-00:00. Dimarts tancat excepte festius.', 'De 07.00h a 00.00h. Martes cerrado excepto festivos.', 'Palma', 'c/ Despuig 7', '971280135', 'www.canllucrestaurant.com', 'entre 10 i 15 â‚¬'),
(5, 'Bodega Llum de Sal', '\nLlum de Sal Ã©s sinÃ²nim de bon gust i tradiciÃ³ en el procÃ©s artesanal de Flor de Sal; noves creacions per gaudir dels sabors i aromes de Mallorca. Celler i botiga delicatessen dirigida i creada per Robert Chaves qui ha sabut fusionar la sal i el vi mallorquÃ­ donant com a resultat un producte exclusiu. Entre els seus productes (biolÃ²gics certificats) destaquen les 13 varietats de salses i 3 d\'ametlles mallorquines.', 'Llum de Sal es sinÃ³nimo de buen gusto y tradiciÃ³n en el proceso artesanal de Flor de Sal; nuevas creaciones para disfrutar de los sabores y aromas de Mallorca. Bodega y tienda delicatessen dirigida y creada por Robert Chaves quien ha sabido fusionar la sal y el vino mallorquÃ­n dando como resultado un producto exclusivo. Entre sus productos (biolÃ³gicos certificados) destacan las 13 variedades de salsas y 3 de almendras mallorquinas. ', 'Tots els dies de 9.30h - 01.00h', 'Todos los dÃ­as de 9.30h - 01.00h', 'Ses Salines', 'Burguera Mut, 14', '971649773', 'www.llumdesal.es', 'entre 15 i 20 â‚¬'),
(6, 'Restaurant Es Quatre Vents', 'Es 4 Vents, inaugurat l\'any 1980, es troba situat a poc mÃ©s d\'un quilÃ²metre de la localitat mallorquina d\'Algaida, a la carretera de Palma a Manacor. Antic bar de l\'estaciÃ³ del tren d\'Algaida ara convertit en restaurant modern i ben equipat on el tracte Ã©s agradable, familiar i summament eficient. Disposen d\'un gran menjador amb diferents estances on es pot celebrar qualsevol tipus d\'esdeveniment familiar, personal ... MenÃºs adequats a les necessitats de cada client. I aquest mateix any han ampliat el restaurant amb una agradable terrassa on poder gaudir alguns dels suculents plats elaborats pel xef.', 'Es 4 Vents, inaugurado en el aÃ±o 1980, se halla situado a poco mÃ¡s de un kilÃ³metro de la localidad mallorquina de Algaida, en la carretera de Palma a Manacor. Antiguo bar de la estaciÃ³n del tren de Algaida ahora convertido en restaurante moderno y bien equipado donde el trato es agradable, familiar y sumamente eficiente. Disponen de un gran comedor con diferentes estancias donde se puede celebrar cualquier tipo de evento familiar, personal... MenÃºs adecuados a las necesidades de cada cliente. Y este mismo aÃ±o han ampliado el restaurante con una agradable terraza donde poder disfrutar algunos de los suculentos platos elaborados por el chef.', 'De 12.30 a 16.00 i de 19.30 a 23.30. Dimarts tancat.', 'De 12.30 a 16.00 y de 19.30 a 23.30. Martes cerrado.', 'Algaida', 'Ctra. Palma-Manacor 21.70km', '971665173', 'www.esquatrevents.com', 'entre 25 i 30 â‚¬'),
(7, 'Piccola Italia', 'La Piccola Italia t\'ofereix un viatge culinari per ItÃ lia a travÃ©s d\'una carta composta per mÃ©s de 120 plats: des de la Pizza mÃ©s sucosa tÃ­pica de Napoli, Spaghetti alla vongole siciliana, a un BacallÃ  a la manera de GÃ¨nova. La pasta, les postres i els gelats sÃ³n artesanals. Tota la pasta que es prepara a Piccola Italia Ã©s fresca i elaborada diÃ riament a la vista del comensal.', 'La Piccola Italia te ofrece un viaje culinario por Italia a travÃ©s de una carta compuesta por mÃ¡s de 120 platos: desde la Pizza mÃ¡s jugosa tÃ­pica de Napoli, Spaghetti alla vongole siciliana, a un Bacalao a la manera de GÃ©nova. La pasta, los postres y los helados son artesanales. Toda la pasta que se prepara en Piccola Italia es fresca y elaborada a diario a la vista del comensal. ', 'Tot l\'any de dilluns a diumenge de 12:30h a 00.30h.', 'Todo el aÃ±o de lunes a domingo de 12:30 a 00.30h.', 'Palma', 'Passeig MarÃ­tim 27', '971458036', 'www.piccolaitaliamallorca.com', 'entre 20 i 25 â‚¬'),
(8, 'S\'Aire', 'El restaurant S\'Aire es troba a Mallorca molt proper a la catedral i al centre de la ciutat de Palma. Destaca per oferir un ambient tÃ­pic mallorquÃ­ grÃ cies a la decoraciÃ³ del local i les seves especialitats culinÃ ries. Es basa en la cuina mallorquina tradicional, i ofereix una gran varietat de tapes, sandvitxos i entrepans en la seva carta a mÃ©s d\'un interessant menÃº del dia amb plats variats. En cadascun dels seus plats s\'utilitzen productes de qualitat i frescos, de la terra.', 'El restaurante Sâ€™Aire se encuentra en Mallorca muy cercano a la catedral y al centro de la ciudad de Palma. Destaca por ofrecer un ambiente tÃ­pico mallorquÃ­n gracias a la decoraciÃ³n del local y sus especialidades culinarias. Se basa en la cocina mallorquina tradicional, y ofrece una gran variedad de tapas, sÃ¡ndwiches y bocadillos en su carta ademÃ¡s de un interesante menÃº del dÃ­a con platos variados. En cada uno de sus platos utilizan productos de calidad y frescos, de la tierra.', 'De 12:00-14:30 i de 20:00 a 24:00h. Dilluns tancat.', 'De 12:00-14:30 y de 20:00 a 24:00h. Lunes cerrado.', 'Palma', 'Gerreria 26', '971451116', 'www.saire.es', 'entre 20 i 25 â‚¬'),
(9, 'Restaurant Corb MarÃ­', 'Des de 1960 Corb MarÃ­ ha acollit a les seves taules una infinitat de comensals que no han quedat indiferents davant la nostra proposta gastronÃ²mica i ubicaciÃ³. Tasteu les nostres autÃ¨ntiques exquisideses, alternant clÃ ssic i contemporani, perÃ² sobretot sense perdre de vista l\'essÃ¨ncia mediterrÃ nia. Disposem d\'una gran selecciÃ³ de carns de primerÃ­ssima qualitat: costella, entrecot, filet de bou, conill, porc, carns ... salsitxes reposades, amb el punt just d\'infiltraciÃ³ de greix, per a paladars exigents.', 'Desde 1960 Corb MarÃ­ ha acogido en sus mesas a infinidad de comensales quienes no han quedado indiferentes ante nuestra propuesta gastronÃ³mica y ubicaciÃ³n. Deguste nuestras autÃ©nticas exquisiteces, alternando clÃ¡sico y contemporÃ¡neo, pero sobretodo sin perder de vista la esencia mediterrÃ¡nea. Disponemos de una gran selecciÃ³n de carnes de primerÃ­sima calidad: chuletÃ³n, entrecot, solomillo de buey, conejo, cerdo, salsichasâ€¦ carnes reposadas, con el punto justo de infiltraciÃ³n de grasa, para paladares exigentes. ', 'Tots els dies de 12 a 23 hores.', 'Todos los dÃ­as de 12 a 23 horas.', 'Port de PollenÃ§a', 'Passeig Anglada Camarassa 91', '971867040', 'www.restaurantcorbmari.com', 'entre 20 i 25 â‚¬'),
(10, 'RacÃ³ de la Bona Cuina', 'RacÃ³ de la Bona Cuina Ã©s un restaurant agradable i de tracte familiar on poder gaudir d\'uns arrossos fantÃ stics i uns menÃºs diaris molt elaborats segons mercat. Als matins, ofereixen uns esmorzars molt complets a molt bon preu, i per les tardes posen a la teva disposiciÃ³ la seva terrassa al costat de la PlaÃ§a d\'Espanya on poder prendre uns gelats, un te o refrescos, i atenciÃ³, totes les begudes van acompanyades d\'una tapa diferent que el xef prepara amb afecte per als seus clients. Disposen de tot aixÃ² en un ambient familiar i agradable on el lema corporatiu Ã©s \"la qualitat no estÃ  renyida amb el preu\" i la seva mÃ xima, sempre cuinar amb afecte.', 'RacÃ³ de la Bona Cuina es una restaurante agradable y de trato familiar donde poder disfrutar de unos arroces estupendos y unos menÃºs diarios muy elaborados segÃºn mercado. Por las maÃ±anas, ofrecen unos desayunos muy completos a muy buen precio, y por las tardes ponen a tu disposiciÃ³n su terraza al lado de la Plaza de EspaÃ±a donde poder tomar unos helados, un tÃ© o refrescos, y atenciÃ³n, todas las bebidas van acompaÃ±adas de una tapa diferente que el chef prepara con cariÃ±o para sus clientes. Disponen de todo esto en un ambiente familiar y agradable donde el lema corporativo es \"la calidad no estÃ¡ reÃ±ida con el precio\" y su mÃ¡xima, siempre cocinar con cariÃ±o. ', 'Dilluns de 8 a 16h i de dimecres a diumenge de 12 a 23:30h. Dimarts tancat.', 'Lunes de 8 a 16h y de miÃ©rcoles a domingo de 12 a 23:30h. Martes cerrado.', 'Palma', 'c/Jafuda Cresques, 6', '971904492', 'www.racodelabonacuina.com', 'entre 10 i 15 â‚¬'),
(11, 'Restaurante GaleÃ³n', 'Restaurant GaleÃ³n es situa enfront de la platja de Llenaire i compta amb unes vistes Ãºniques a la Badia del Port de PollenÃ§a. Ofereix MenÃº diari, Snacks i A la Carta. Obert tots els dies. Servei per a celebracions de grups, casaments i esdeveniments. No podeu deixar de provar les carns servides a la pedra volcÃ nica, la lasanya de llagosta o les delicioses paelles. Per a grups mÃ­nim 10 persones Ã©s imprescindible prÃ¨via reserva. Ofereixen diferents opcions de menÃº i pressupost..', 'Restaurante GaleÃ³n se ubica frente a la playa de Llenaire y cuenta con unas vistas Ãºnicas a la BahÃ­a del Puerto de PollenÃ§a.  Ofrece MenÃº diario, Snacks y A la Carta. Abierto todos los dÃ­as. Servicio para celebraciones de grupos, bodas y eventos. No podÃ©is dejar de probar las carnes servidas a la piedra volcÃ¡nica, la lasaÃ±a de langosta o las deliciosas paellas. Para grupos mÃ­nimo 10 personas es imprescindible previa reserva. Ofrecen diferentes opciones de menÃº y presupuesto.', 'Esmorzars: 08:00-10:00h. Cafeteria, Snacks i MenÃº diari: 12:30-16:00h. Sopars: 18:30-22:30h.', 'Desayunos: 08:00-10:00h. CafeterÃ­a, Snacks y MenÃº diario: 12:30-16:00h. Cenas: 18:30-22:30h.', 'Port de PollenÃ§a', 'Passeig de Londres 84-86', '971105575', 'www.restaurantegaleon.com', 'entre 15 i 20 â‚¬'),
(12, 'El Gallego', 'Ã‰s un lloc especial, tradicional i molt familiar amb especialitats tan saboroses com pop amb cachelos, empanada, pebrots, petxines variades, salpicÃ³, gambes, lluÃ§ de palangre, bacallÃ , mitjana a la pedra, costelletes, cabrit de llet, lacÃ³n amb grelos, cua de bou i lletons de vedella. TÃ­pic menjar gallega elaborada amb productes de primera qualitat en una amplÃ­ssima carta: peixos, carns, triperia i racions. Compten amb menÃº diari i menÃºs de grup..', 'Es un lugar especial, tradicional y muy familiar con especialidades tan sabrosas como pulpo con cachelos, empanada, pimientos, zamburiÃ±as, salpicÃ³n, gambas, merluza de pincho, bacalao, chuletÃ³n a la piedra, chuletitas, cabrito lechal, lacÃ³n con grelos, rabo de buey y mollejas de ternera. TÃ­pica comida gallega elaborada con productos de primera calidad en una amplÃ­sima carta: pescados, carnes, casquerÃ­a y raciones. Cuentan con menÃº diario y menÃºs de grupo. ', 'Tots els dies de 13:00-16: 00h. Dijous, divendres i dissabtes de 13:00-16:00 / 20:00-00:00h.', 'Todos los dÃ­as de 13:00-16:00h. Jueves, viernes y sÃ¡bados de 13:00-16:00 / 20:00-00:00h.', 'Palma', 'c/ Del Carmen 16', '971710313', 'www.restaurante-elgallego.es', 'entre 20 i 25 â‚¬'),
(13, 'Es Castell: Castillo Hotel Son Vida', 'En un lloc emblemÃ tic ple d\'histÃ²ria i tradiciÃ³, al Castell Hotel Son Vida, es troba el Restaurant Es Castell. Assaboreix menjar tradicional presentat amb un toc modern i amb productes locals mentre gaudeixes de les vistes a la badia de Palma i la seva catedral la Seu. Hi predomina la cuina espanyola amb influÃ¨ncies mediterrÃ nies acompanyades pels millors vins mallorquins i internacionals seleccionats pel Cap Sommelier Felix Granado amb gran coneixement de l\'enologia farÃ  que la teva experiÃ¨ncia culinÃ ria sigui completa.', 'En un lugar emblemÃ¡tico lleno de historia y tradiciÃ³n, en el Castillo Hotel Son Vida, se encuentra el Restaurante Es Castell. Saborea comida tradicional presentada con un toque moderno y con productos locales mientras disfrutas de las vistas a la bahÃ­a de Palma y su catedral La Seu. Predomina la cocina espaÃ±ola con influencias mediterrÃ¡neas acompaÃ±adas por los mejores vinos mallorquines e internacionales seleccionados por el Jefe Sumiller Felix Granado cuyo gran conocimiento de la enologÃ­a harÃ¡ que tu experiencia culinaria sea completa. ', 'Esmorzar: 7:00-11:00h, Sopar: 19:00-22:30h.', 'Desayuno: 7:00-11:00h, Cena: 19:00-22:30h.', 'Palma', 'Carrer de la Raixa 2', '971493493', 'www.castillosonvidamallorca.com', 'entre 40 i 50 â‚¬'),
(14, 'Arume Restaurant Sushi Bar', 'El xef Tomeu MartÃ­, sempre a l\'avantguarda de la cuina de l\'illa, reinterpreta la cuina japonesa amb un toc mediterrani realment original, la seva constant investigaciÃ³ ens permet redescobrir tots els sabors de la fusiÃ³ Orient-Occident. Aquest local Ã©s una referÃ¨ncia dels restaurants japonesos, situat al centre de la ciutat de Palma, la seva cuina ens descobreix un ampli recorregut per la gastronomia nipona, donant-nos a conÃ¨ixer sabors Ãºnics en plats molt creatius que resulten sans per al cos i gratificants per l\'Ã nima..', 'El chef Tomeu MartÃ­, siempre a la vanguardia de la cocina de la isla, reinterpreta la cocina japonesa con un toque mediterrÃ¡neo realmente original, su constante investigaciÃ³n nos permite redescubrir todos los sabores de la fusiÃ³n Oriente-Occidente. Este local es una referencia de los restaurantes japoneses, situado en el centro de la ciudad de Palma, su cocina nos descubre un amplio recorrido por la gastronomÃ­a nipona, dÃ¡ndonos a conocer sabores Ãºnicos en platos muy creativos que resultan sanos para el cuerpo y gratificantes para el alma.', 'De dilluns a dissabtes: 13.30 a 15.30h i 20.30 a 23h. Diumenges i festius tancat.', 'De lunes a sÃ¡bados: 13.30 a 15.30h y 20.30 a 23h. Domingos y festivos cerrado.', 'Palma', 'San Miguel, 83', '971214121', 'www.arume-sushi.com', 'entre 30 i 40 â‚¬'),
(15, 'Es Convent d\'Ariany', 'El restaurant Es Convent estÃ  ubicat a les instalÂ·lacions d\'un modern i acollidor hotel d\'interior. Es Convent d\'Ariany, localitzat al poble del mateix nom. El seu disseny i aposta gastronÃ²mica s\'alineen en una contÃ­nua recerca i disseny d\'experiÃ¨ncies en les que el resultat sigui un producte que unifiqui exclusivitat i sabor. El marc incomparable en quÃ¨ es localitza, amb vistes privilegiades sobre el Pla de Mallorca, Ã©s l\'espai perfecte per relaxar-se i degustar les propostes del xef Joan Vila..', 'El restaurante Es Convent estÃ¡ ubicado en las instalaciones de un moderno y acogedor hotel de interior. Es Convent dâ€™Ariany, localizado en el pueblo del mismo nombre. Su diseÃ±o y apuesta gastronÃ³mica se alinean en una continua bÃºsqueda y diseÃ±o de experiencias en las que el resultado sea un producto que unifique exclusividad y sabor. El marco incomparable en que se localiza, con vistas privilegiadas sobre el Pla de Mallorca, es el espacio perfecto para relajarse y degustar las propuestas del chef Joan Vila. ', 'Tots els dies de 19:30h a 23:00h. Divendres, Dissabtes i Diumenges de 13:30h a 16:00h.', 'Todos los dÃ­as de 19:30h a 23:00h. Viernes, SÃ¡bados y Domingos de 13:30h a 16:00h.', 'Ariany', 'Carrer Major 2', '691473379', 'www.esconvent.org', 'entre 20 i 25 â‚¬'),
(16, 'Restaurant MolÃ­ des Torrent', 'El nostre molÃ­ histÃ²ric i reformat ofereix la ubicaciÃ³ ideal per organitzar festes d\'aniversari, casaments o reunions de negocis. Al restaurant i el pati tambÃ© pot passar un inoblidable sopar a la llum de les espelmes per a dues persones.', 'Nuestro molino histÃ³rico y cuidadosamente restaurado ofrece la ubicaciÃ³n perfecta para celebrar cumpleaÃ±os, bodas o reuniones de negocios. En el restaurante y nuestro patio tambiÃ©n puede pasar una inolvidable cena a la luz de las velas para dos.', 'De dilluns a dissabtes: 12.30 a 15.30h i 20.30 a 23h. Diumenges i festius tancat.', 'De lunes a sÃ¡bados: 12.30 a 15.30h y 20.30 a 23h. Domingos y festivos cerrado.', 'Santa Maria', 'Carretera de Bunyola 75', '971140503', 'www.molidestorrent.de', 'entre 20 i 25 â‚¬'),
(17, 'Restaurant Sa PlaÃ§a Petra', 'Al restaurant Sa PlaÃ§a Petra es desenvolupa una deliciosa cuina d\'autor i antiga cuina mallorquina, de manera que es pot dir que es tracta d\'un restaurant autÃ¨ntic mallorquÃ­, amb el menjar casolÃ  i tradicional de tota la vida, seguint les receptes d\'antany, perÃ² innovant amb tocs d\'autor que fan els seus plats Ãºnics..', 'En el restaurante Sa PlaÃ§a Petra se desarrolla una deliciosa cocina de autor y antigua cocina mallorquina, por lo que se puede decir que se trata de un restaurante autÃ©ntico mallorquÃ­n, con la comida casera y tradicional de toda la vida, siguiendo las recetas de antaÃ±o, pero innovando con toques de autor que hacen sus platos Ãºnicos. ', 'Dilluns de 8 a 16h i de dimecres a diumenge de 12 a 23:30h. Dimarts tancat.', 'Lunes de 8 a 16h y de miÃ©rcoles a domingo de 12 a 23:30h. Martes cerrado.', 'Petra', 'c/ Ramon Llull 4', '971561646', 'www.petithotelpetra.com', 'mÃ©s de 50 â‚¬'),
(18, 'Ristorante Brunello', 'Menjar al restaurant Brunello et transporta a una altra Ã¨poca ... Les seves parets estan decorades amb pintures murals de l\'Ã¨poca grega i romana. Decorat amb una exquisida elegÃ ncia, sense fum, ambient relaxat, tracte molt cuidat i excelÂ·lent atenciÃ³ per part dels cambrers..', 'Comer en el restaurante Brunello te transporta a otra Ã©poca... Sus paredes estÃ¡n decoradas con pinturas murales de la Ã©poca griega y romana. Decorado con una exquisita elegancia, sin humo, ambiente relajado, trato muy cuidado y excelente atenciÃ³n por parte de los camareros. ', 'Tots els dies de 13:30 a 15:30h.', 'Todos los dÃ­as de 13:30 a 15:30h.', 'Palma', 'c/Santiago RamÃ³n y Cajal, 15 ', '971221424', 'www.brunelloitalianrestaurant.com', 'entre 30 i 40 â‚¬'),
(19, 'Can Joan Capo', 'Al nostre restaurant podrÃ  degustar cuina basada en la dieta mediterrÃ nia, amb elaboracions i receptes tÃ­piques actualitzades, sense oblidar altres conceptes i tÃ¨cniques. El nostre xef elabora diÃ riament delicioses exquisideses mantenint sempre el mÃ xim respecte pels productes autÃ²ctons, de temporada i sobretot frescos. El nostre objectiu Ã©s que puguin gaudir d\'un dinar o sopar sorprenent en un ambient amb carÃ cter. Gaudir menjant Ã©s la millor manera d\'aturar el temps. Treballem perquÃ¨ ho aconsegueixi entre nosaltres.', 'En nuestro restaurante podrÃ¡ degustar cocina basada en la dieta mediterrÃ¡nea, con elaboraciones y recetas tÃ­picas actualizadas, sin olvidar otros conceptos y tÃ©cnicas. Nuestro chef elabora diariamente deliciosas exquisiteces manteniendo siempre el mÃ¡ximo respeto por los productos autÃ³ctonos, de temporada y sobretodo frescos. Nuestro objetivo es que puedan disfrutar de una comida o cena sorprendente en un ambiente con carÃ¡cter. Disfrutar comiendo es la mejor forma de detener el tiempo. Trabajamos para que lo consiga entre nosotros.', 'Tots els dies de 13:30 a 15:30h.', 'Todos los dÃ­as de 13:30 a 15:30h.', 'Sineu', 'DegÃ  Joan Rotger,4', '971855075', 'www.canjoancapo.com', 'entre 40 i 50 â‚¬'),
(20, 'Vietnam CafÃ©', 'Vietnam CafÃ¨ va obrir les seves portes a Palma desprÃ©s d\'una visita dels seus propietaris a aquest mateix paÃ­s el 2004. Van quedar impressionats amb els seus paisatges, les seves gents i els productes naturals i els meravellosos sabors de la cuina vietnamita. A Vietnam CafÃ¨, el seu cap de cuina Tuan Thin i el seu ajudant Dhuong Tahng elaboren una cuina autÃ²ctona fidel a la seva tradiciÃ³ i transporten als seus clients a aquest llunyÃ  paÃ­s. Molts dels ingredients sÃ³n importats d\'Ã€sia, alguns Vietnam com lemongrass, fulles de llima, tamarinde i grans de lotus. L\'aperitiu estrella sÃ³n els rotllets de primavera coneguts com \'nems\'. Estan fets amb pasta d\'arrÃ²s i s\'elaboren amb diversos ingredients (segons la zona del peix, vegetals, pollastre).', 'ViÃ©tnam CafÃ© abriÃ³ sus puertas en Palma despuÃ©s de una visita de sus propietarios a ese mismo paÃ­s en 2004. Quedaron impresionados con sus paisajes, sus gentes y los productos naturales y los maravillosos sabores de la cocina vietnamita. En ViÃ©tnam CafÃ©, su jefe de cocina Tuan Thin y su ayudante Dhuong Tahng elaboran una cocina autÃ³ctona fiel a su tradiciÃ³n y transportan a sus clientes a ese lejano paÃ­s. Muchos de los ingredientes son importados de Asia, algunos de Vietnam como lemongrass, hojas de lima, tamarindo y granos de loto. El aperitivo estrella son los rollitos de primavera conocidos como \'nems\'. EstÃ¡n hechos con pasta de arroz y se elaboran con diversos ingredientes (segÃºn la zona del pescado, vegetales, pollo).', 'De dimarts a diumenge de 13:00 a 15: 30h i de 20: 00h a 23: 30h. Dilluns tancat.', 'De martes a domingo de 13:00 a 15:30h y de 20:00h a 23:30h. Lunes cerrado.', 'Palma', 'PlaÃ§a ProgrÃ©s, 14', '971285023', 'www.vietnamcafe.es', 'entre 25 i 30 â‚¬');

--
-- Índexs per a les taules bolcades
--

--
-- Índexs per a la taula `establiment`
--
ALTER TABLE `establiment`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT per les taules bolcades
--

--
-- AUTO_INCREMENT per la taula `establiment`
--
ALTER TABLE `establiment`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
